CREATE DATABASE OLA_PROJECT 
USE OLA_PROJECT

SELECT * FROM Bookings

-- 1)RETRIVE ALL SUCCESSFULL BOOKINGS 

CREATE VIEW SUCCESSFULL_BOOKINGS AS
SELECT * FROM Bookings
WHERE Booking_Status='Success';

SELECT * FROM SUCCESSFULL_BOOKINGS

--2)FIND THE AVERAGE RIDE DISTANCE FOR EACH VEHICAL TYPE 
CREATE VIEW RIDE_DISTANCE_FOR_EACH_VEHICAL_TYPE AS
SELECT VEHICLE_TYPE ,AVG(RIDE_DISTANCE) AVG_DIS
FROM Bookings
GROUP BY VEHICLE_TYPE;

SELECT * FROM RIDE_DISTANCE_FOR_EACH_VEHICAL_TYPE

--3 GET THE TOTAL NUMBER OF CANCELLED RIDES BY CUSTOMERS:

CREATE VIEW TOTAL_NUMBER_OF_CANCELLED_RIDES_BY_CUSTOMERS AS
SELECT COUNT(*) TOTAL
FROM BOOKINGS 
WHERE  BOOKING_STATUS = 'Canceled by Customer'

SELECT * FROM TOTAL_NUMBER_OF_CANCELLED_RIDES_BY_CUSTOMERS

--4)LIST THE TOP 5 CUSTOMERS WHO BOOKED THE HIGHEST NUMBER OF RIDES:

CREATE VIEW   TOP_5_CUSTOMERS_WHO_BOOKED_THE_HIGHEST_NUMBER_OF_RIDES AS
SELECT TOP 5 CUSTOMER_ID,COUNT(BOOKING_ID) AS Total_Rides
FROM BOOKINGS
GROUP BY CUSTOMER_ID
ORDER BY Total_Rides DESC;

SELECT * FROM TOP_5_CUSTOMERS_WHO_BOOKED_THE_HIGHEST_NUMBER_OF_RIDES

--5)GET THE NUMBER OF RIDES CANCELLED BY DRIVERS DUE TO PERSONAL AND CAR-RELATED ISSUES:
CREATE VIEW CANCELLED_BY_DRIVERS AS
SELECT  COUNT(*) CANCELLED_BY_DRIVERS
FROM Bookings
WHERE Canceled_Rides_by_Driver='Personal & Car related issue'

SELECT * FROM CANCELLED_BY_DRIVERS

--6)FIND THE MAXIMUM AND MINIMUM DRIVER RATINGS FOR PRIME SEDAN BOOKINGS:

--[MIN]
SELECT MIN(Driver_Ratings) AS MINIMUM_RATING
FROM Bookings
WHERE Vehicle_Type='Prime Sedan'

--[MAX]
SELECT MAX(Driver_Ratings) AS MINIMUM_RATING
FROM Bookings
WHERE Vehicle_Type='Prime Sedan'

CREATE VIEW MIN_MAX_DRIVER_RATINGS_FOR_PRIME_SEDAN_BOOKINGS AS
SELECT MAX(Driver_Ratings) as max_rating, MIN(Driver_Ratings) as min_rating FROM
bookings WHERE Vehicle_Type = 'Prime Sedan';

SELECT * FROM MIN_MAX_DRIVER_RATINGS_FOR_PRIME_SEDAN_BOOKINGS

--7)RETRIEVE ALL RIDES WHERE PAYMENT WAS MADE USING UPI:
CREATE VIEW PAYMENT_MODE_UPI AS
SELECT  Date , Time ,Booking_ID ,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,Booking_Value,Payment_Method FROM Bookings
WHERE Payment_Method='UPI';

SELECT * FROM PAYMENT_MODE_UPI

--8)FIND THE AVERAGE CUSTOMER RATING PER VEHICLE TYPE

SELECT Vehicle_Type,AVG(Customer_Rating) AVG_CUSTOMER_RATING
FROM Bookings
GROUP BY Vehicle_Type;

--9)CALCULATE THE TOTAL BOOKING VALUE OF RIDES COMPLETED SUCCESSFULLY

CREATE VIEW TOTAL_BOOKING_VALUE_FOR_COMPLETED_SUCESSFULLY AS
SELECT SUM(Booking_Value) TOTAL_BOOKING_VALUE
FROM Bookings
WHERE Booking_Status='Success'

SELECT * FROM TOTAL_BOOKING_VALUE_FOR_COMPLETED_SUCESSFULLY
--(I)TOTAL BOOKING VALUE AS PER VEHICAL TYPE 
CREATE VIEW TOTAL_BOOKING_VALUE_AS_PER_VEHICAL_TYPE AS
SELECT Vehicle_Type ,SUM(Booking_Value) TOTAL_BOOKING_VALUE
FROM Bookings
WHERE Booking_Status='Success'
GROUP BY Vehicle_Type

SELECT * FROM TOTAL_BOOKING_VALUE_AS_PER_VEHICAL_TYPE

--10)LIST ALL INCOMPLETE RIDES ALONG WITH THE REASON:

CREATE VIEW INCOMPLETE_RIDE_WITH_REASON AS
SELECT Booking_ID, Incomplete_Rides_Reason 
FROM bookings 
WHERE Incomplete_Rides ='1';

SELECT * FROM INCOMPLETE_RIDE_WITH_REASON;






SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'BOOKINGS';